### ISSUE TITLE
issue about data

### ISSUE THREAD

**Issue by 996237275** [MingxuanGu/Few-shot-UDA#2]
Thank you for your interesting work!
While I have some questions about the path of data directory. After using the script which you mentioned on the data, I put them on `../data`. 
![image](https://github.com/MingxuanGu/Few-shot-UDA/assets/44522453/e9c66b01-8d2c-4de8-8f9a-0f77aa66706c)
However, I found the `data_generator_RAIN.py` cannot find the correct way of dataset. I tried several methods including using abspath but they cannot work.
Looking for your kindly reply!

**Comment by MingxuanGu** [comment]
`../` means the parent directory of the current directory. So if your root directory is `Few-shot-UDA-main/`, then `../` means the parent directory of `Few-shot-UDA-main`. You can also print out the abs path of `../data` to find out exactly where it is. Hope it helps.

**Comment by 996237275** [comment]
Thank you for your reply and the problem had been solved. 
I would like to know trainA, trainB... etc. folders contain those images of the patient, the data_readme.txt included in the dataset you provided only contains a description of the TRAIN DATA and TEST DATA. Looking forward to your reply.

**Comment by MingxuanGu** [comment]
Hi, I updated the "Data structure" in the "Data" section in the README.md. Hope it answers your question.

**Comment by 996237275** [comment]
Thanks.
Through the code you prodvided for transfering nii to png, I found that the T2/bssfp images do not have the corresponding mask from pat_35 to 45. So the data_generator.py will assert len(image)!=len(mask)

**Comment by 996237275** [comment]
![image](https://github.com/MingxuanGu/Few-shot-UDA/assets/44522453/e4c6a9bd-ae3a-4b5c-b8b3-a64d0ce13306)

**Comment by MingxuanGu** [comment]
Please check `preprocess_data.py`. You may still need to modify the paths to run the code.

**Comment by 996237275** [comment]
Is it because the dataset I downloaded doesn't match your original dataset? The manual file for bssfp in the dataset I downloaded is only 1-35
![image](https://github.com/MingxuanGu/Few-shot-UDA/assets/44522453/d67e0f07-23fd-43cb-9bf7-bb6e4a4863cf)

**Comment by MingxuanGu** [comment]
Did you download the data set following the instruction on this website https://zmiclab.github.io/zxh/0/mscmrseg19/ ? Have you also downloaded the test set? If there is still a problem with the data set, please don't hesitate to contact the data holder for more information.

**Comment by 996237275** [comment]
Sorry, I hadn't download the testset. The link for both trainset and testset are unavailable now.

**Comment by 996237275** [comment]
[https://zmiclab.github.io/projects/mscmrseg19/ ](url) and [http://www.sdspeople.fudan.edu.cn/zhuangxiahai/0/mscmrseg19/](url) are unavailable.

**Comment by MingxuanGu** [comment]
Maybe they moved the data set. Please ask the Fudan ZMIC lab team for more information about the data set.

**Comment by 996237275** [comment]
`Traceback (most recent call last):
  File "/root/data1/UPPER/gyx_torch/Few-shot-UDA-main/train_RAIN.py", line 205, in <module>
    main()
  File "/root/data1/UPPER/gyx_torch/Few-shot-UDA-main/utils/timer.py", line 15, in timefunc
    result = func(*args, **kwargs)
  File "/root/data1/UPPER/gyx_torch/Few-shot-UDA-main/train_RAIN.py", line 180, in main
    decoder_checkpoint.step(monitor=monitor, model=network.decoder, epoch=i + 1)
  File "/root/data1/UPPER/gyx_torch/Few-shot-UDA-main/utils/callbacks.py", line 79, in step
    'optimizer_state_dict': opt_to_save}, self.best_model_dir)
UnboundLocalError: local variable 'opt_to_save' referenced before assignment`
Have you ever had this problem?

**Comment by MingxuanGu** [comment]
That's weird. Normally, the `opt_to_save` will be assigned at the beginning of the function `step()`. Could you please debug the code?

**Comment by 996237275** [comment]
`    def step(self, monitor, model, epoch, optimizer=None, tobreak=False):
        """
        Check the monitor score with the previously saved best score and save the currently best model
        Args:
            monitor: the score used for monitoring
            model: the model to be saved
            epoch: the current epoch number
            optimizer: the optimizer of the model (only used to recover the training state when load the model)
            tobreak: whether reach the last epoch

        Returns:
        """
     
        if self.entire_model:
            to_save = model
            opt_to_save = optimizer
        else:
            to_save = model.state_dict()
            if optimizer is not None:
                opt_to_save = optimizer.state_dict()
            else:
                opt_to_save=None`
This is part of the code.
I added `opt_to_save=None` in the begining of `step()` while it didnot work.
